### ISSUE TITLE
Not loading games

### ISSUE THREAD

**Issue by HttpAnimation** [arianrhodsandlot/retro-assembly#2]
Getting a issue saying could not load games when opening the site I have my drive set up like this
/
~/Roms
~~/NES
~~~452 Fies
~~/SNES
~~~323 FileS
~~/PS1
```/Empty

**Comment by arianrhodsandlot** [comment]
Is this problem still present when using any other browsers? If not, could you please provide more information such as the steps for reproducing the issue，or a screenshot / screen record with browser console opened?
Here are instructions on how to provide sufficient information so that I may assist you more effectively.: https://antfu.me/posts/why-reproductions-are-required

**Comment by HttpAnimation** [comment]
Found out the cashed to had be to cleared
